import { z } from "zod";

/**
 * A link to a built-in batch job.
 *  Batch jobs can be used to perform operations on a set of workflows (e.g. terminate, signal, cancel, etc).
 *  This link can be put on workflow history events generated by actions taken by a batch job.
 */
export const Link_BatchJobSchema = z
  .object({ jobId: z.string().optional() })
  .describe(
    "A link to a built-in batch job.\n Batch jobs can be used to perform operations on a set of workflows (e.g. terminate, signal, cancel, etc).\n This link can be put on workflow history events generated by actions taken by a batch job.",
  );
export type Link_BatchJobSchema = z.infer<typeof Link_BatchJobSchema>;
